// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv8nDGrUzYgJHl9C3AnN8p6HgNnhIhGPo',
    appId: '1:982387692160:web:5fc797e1ae2912152e4c65',
    messagingSenderId: '982387692160',
    projectId: 'bus-ticketing-cf49f',
    authDomain: 'bus-ticketing-cf49f.firebaseapp.com',
    storageBucket: 'bus-ticketing-cf49f.firebasestorage.app',
    measurementId: 'G-X7H6T5KQKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiJynFiegK52OgeuDR_IT3ic2j0Rahz3A',
    appId: '1:982387692160:android:ce50c772befdeee32e4c65',
    messagingSenderId: '982387692160',
    projectId: 'bus-ticketing-cf49f',
    storageBucket: 'bus-ticketing-cf49f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BalTqOidiReucWNLqCAP4MA1-pRJvfM',
    appId: '1:982387692160:ios:146b526a0ecef2922e4c65',
    messagingSenderId: '982387692160',
    projectId: 'bus-ticketing-cf49f',
    storageBucket: 'bus-ticketing-cf49f.firebasestorage.app',
    iosBundleId: 'com.example.busTicketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0BalTqOidiReucWNLqCAP4MA1-pRJvfM',
    appId: '1:982387692160:ios:146b526a0ecef2922e4c65',
    messagingSenderId: '982387692160',
    projectId: 'bus-ticketing-cf49f',
    storageBucket: 'bus-ticketing-cf49f.firebasestorage.app',
    iosBundleId: 'com.example.busTicketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv8nDGrUzYgJHl9C3AnN8p6HgNnhIhGPo',
    appId: '1:982387692160:web:00015fa4288322a62e4c65',
    messagingSenderId: '982387692160',
    projectId: 'bus-ticketing-cf49f',
    authDomain: 'bus-ticketing-cf49f.firebaseapp.com',
    storageBucket: 'bus-ticketing-cf49f.firebasestorage.app',
    measurementId: 'G-XFE4P9NYHV',
  );

}